-- Nhập dữ liệu khách hàng + lịch sử tương tác cũ từ Lark Base "CRM KHÁCH HÀNG – HỆ SINH THÁI
-- HIỂU" (chị Quỳnh xuất file Excel gửi 2026-08-29) vào Trợ Lý AI Tư Vấn & CRM
-- (crm_customers/crm_interactions). Chạy 1 LẦN trong Supabase SQL Editor (bỏ qua RLS nên
-- không cần đăng nhập). Gắn dữ liệu vào đúng user có email dưới đây (ruby.tuquynh911@gmail.com —
-- email đăng nhập THẬT của chị Quỳnh ở app, KHÁC với email nhận diện trong hệ thống Claude).
--
-- form_hd: 4/8 khách đã có sẵn khung F-O-R-M-H-D trong ghi chú AI cũ của Lark (Quế Chi, Dương
-- Ngọc Hà, Hạnh Phạm, Thanh Hưởng) — tách ra đúng cột form_hd mới thay vì để chung trong
-- ghi_chu_ai. nhanh suy ra từ nhóm nhu cầu/ghi chú gốc (không bịa — Shino Nguyễn ghi rõ
-- "Nhánh B", Lê Đình Cả ghi rõ "Nhánh KINH DOANH/ĐỐI TÁC"=D, còn lại theo đúng nhóm nhu cầu).
--
-- CỐ TÌNH BỎ QUA 17 dòng tương tác trong sheet "NHẬT KÝ TƯƠNG TÁC" không gắn tên khách (toàn
-- bộ về chủ đề sức khỏe/mất ngủ + 1 lead kinh doanh chưa rõ tên) — đây là lead ẩn danh chưa
-- từng được tạo hồ sơ khách chính thức trong Lark, và crm_interactions bắt buộc phải gắn
-- đúng 1 customer_id có thật nên không tự tạo hồ sơ giả để gắn vào.
do $$
declare
  v_user_id uuid;
  v_mai_huong uuid;
  v_thu_tham uuid;
  v_que_chi uuid;
  v_ngoc_ha uuid;
  v_hanh_pham uuid;
  v_thanh_huong uuid;
  v_dinh_ca uuid;
  v_shino uuid;
begin
  select id into v_user_id from auth.users where email = 'ruby.tuquynh911@gmail.com';
  if v_user_id is null then
    raise exception 'Khong tim thay user voi email ruby.tuquynh911@gmail.com - kiem tra lai truoc khi chay.';
  end if;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Nguyễn Mai Hương', 'Quỳnh Tú', 'Facebook', 'https://www.facebook.com/huong.nguyen.50702', 'C', array['Khoá Xây nhân hiệu','Khoá Sản phẩm số'], null, null, 'Chốt', 'Nóng', array[]::text[], null, null, null, null, null, null, null, null)
  returning id into v_mai_huong;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Nguyễn Thị Thu Thắm', 'Quỳnh Tú', 'Facebook Messenger', 'https://www.facebook.com/ThuTham6789', 'C', array['Xây nhân hiệu','Coaching 1:1'], 'Muốn xây thương hiệu cá nhân theo hướng tâm linh – sức khỏe; mong được Tú Quỳnh coaching 1:1, cầm tay chỉ việc, định vị kênh, hướng dẫn quay video/content và xây phễu dòng tiền.', 'Không phù hợp cách học online/video dài và không muốn học chủ yếu qua trợ lý; cần tương tác trực tiếp, hướng dẫn sát từ đầu. Đã có trải nghiệm tu tập và muốn chuyển trải nghiệm/sứ mệnh thành hướng xây kênh rõ ràng.', 'Đã mua / đang onboarding', 'Nóng', array['Không phù hợp học online','Muốn trực tiếp 1:1 với Tú Quỳnh','Trải nghiệm ban đầu với trợ lý chưa phù hợp'], 'Ưu tiên coaching trực tiếp 1:1 để định vị kênh và xây kế hoạch triển khai cá nhân; sau đó tích hợp các phần nền tảng cần thiết của chương trình Xây Nhân Hiệu theo khả năng tiếp nhận của khách.', '2026-08-07', '2026-08-20', 'Chốt lại lịch gặp trực tiếp sau khi khách đi Nha Trang về; trước buổi gặp yêu cầu khách hoàn thiện bài Câu chuyện gốc/biến cố 31–33 để dùng làm dữ liệu định vị kênh.', '8.900.000đ', null, 'SỰ THẬT: Khách nói sứ mệnh muốn đi theo tâm linh – sức khỏe, ''khai tâm mở tuệ cho đời''; đã tu tập tại các nơi thánh địa Phật khoảng 3 năm, giúp nhiều bạn trẻ tu tập, từng tìm hiểu luân xa/năng lượng/Reiki. Khách yêu cầu ngay từ đầu học 1:1 và không học online; đã chuyển 8,9M. Khách có con và có lịch đi Nha Trang, sau khi về sẽ hẹn tiếp. SUY LUẬN AI: khách có động lực và câu chuyện cá nhân mạnh, phù hợp xây nhân hiệu dựa trên trải nghiệm thật; rủi ro chính là lệch kỳ vọng dịch vụ nên cần tái xác nhận rõ phạm vi coaching trước khi triển khai tiếp.', null)
  returning id into v_thu_tham;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Quế Chi', 'Quỳnh Tú', 'Zalo', 'https://www.facebook.com/tranthiquechicom', 'D', array['Sức khoẻ','Cơ hội kinh doanh'], 'Muốn giảm cân/cải thiện sức khỏe; đồng thời muốn xây lại sự nghiệp, phát triển online, sức khỏe và hệ thống; định hướng xây hệ sinh thái riêng và xem MLM như một phần trong hệ sinh thái.', 'Từng đạt thu nhập khoảng 300 triệu/tháng khi làm bảo hiểm nhưng hiện thu nhập tái tục khoảng 3–5 triệu/tháng, đang trả nợ và chưa có tích lũy; muốn lấy lại đà sự nghiệp và cải thiện sức khỏe.', 'Đang tư vấn', 'Nóng', array['Khác'], null, '2026-08-07', '2026-08-08', 'Đã nhắn follow sau video nhưng chưa phản hồi; nếu đến 08/08/2026 vẫn im lặng, follow ngắn hỏi cảm nhận về video/phần thấy phù hợp nhất và đề nghị hẹn review, không nói giá hay cam kết thu nhập.', null, 'Chưa chốt', 'Thông tin bổ sung 07/08: Quế Chi bằng tuổi Tú Quỳnh; video giới thiệu mô hình đã được gửi trước đó, nên bước tiếp theo là review sau video, không gửi lại video.', '{"gia_dinh": "Chưa có thông tin gia đình/người ảnh hưởng quyết định.", "cong_viec": "11 năm Dai-ichi; từng đạt khoảng 300 triệu/tháng năm 2021; hiện ở quê, thu nhập tái tục khoảng 3–5 triệu/tháng.", "so_thich_quan_he": "Mong muốn giúp 1000 phụ nữ sống tự chủ tài chính và hạnh phúc.", "money": "Đang trả nợ, chưa có tích lũy; mục tiêu khách tự đặt là quay lại 300 triệu/tháng trong 6–12 tháng, cần hiệu chỉnh kỳ vọng, không cam kết thu nhập.", "suc_khoe": "Cao 1m53, 63kg; muốn giảm cân/cải thiện sức khỏe.", "mong_muon": "Muốn xây lại sự nghiệp, hệ sinh thái riêng, phát triển online–sức khỏe–hệ thống."}'::jsonb)
  returning id into v_que_chi;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Dương Ngọc Hà', 'Quỳnh Tú', 'Facebook', 'https://www.facebook.com/ngocha.duong.5895', 'D', array['Cơ hội kinh doanh'], 'Đã tham gia VIP kinh doanh và làm công việc kinh doanh cùng Tú Quỳnh; cần reconnect và cập nhật lại tình hình sau thời gian dài ít tham gia hoạt động/Zoom.', 'Giai đoạn trước liên tục có việc gia đình và sức khỏe làm gián đoạn hoạt động: chồng ốm, con bệnh/con mổ ruột thừa, con gái ốm; bản thân từng bị dị ứng da nặng và bỏ lỡ chương trình đào tạo cùng team.', 'Chăm sóc', 'Ấm', array[]::text[], null, '2026-08-07', '2026-08-10', 'Chờ phản hồi tin nhắn reconnect; nếu chưa phản hồi, follow nhẹ ngày 10/08/2026, hỏi thăm tình hình hiện tại và mục tiêu trước khi bàn nhịp quay lại kinh doanh.', null, 'Đã chốt', 'Thông tin lịch sử do Tú Quỳnh cung cấp: khách đã vào VIP kinh doanh và đã làm công việc kinh doanh cùng Tú Quỳnh. Hà kém tuổi Tú Quỳnh, khi soạn tin nên xưng chị–em phù hợp. Trước đây đã xem video, chủ động inbox Zalo chia sẻ; từng có xét nghiệm máu và cập nhật tuần thứ 2. Giai đoạn sau gặp nhiều gián đoạn gia đình/sức khỏe và ít vào Zoom.', '{"gia_dinh": "Có chồng và con; gia đình từng có nhiều vấn đề sức khỏe làm gián đoạn công việc.", "cong_viec": "Đã tham gia kinh doanh cùng Tú Quỳnh; chi tiết nghề nghiệp/tiến độ hiện tại chưa cập nhật.", "so_thich_quan_he": "Chưa có.", "money": "Chưa có dữ liệu hiện tại.", "suc_khoe": "Từng có xét nghiệm máu; từng bị dị ứng da nặng; tình trạng hiện tại chưa cập nhật.", "mong_muon": "Trước đây cần được kéo lại về mục tiêu/ước mơ và hình ảnh người mình muốn trở thành; mục tiêu cụ thể hiện tại chưa cập nhật."}'::jsonb)
  returning id into v_ngoc_ha;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Hạnh Phạm', 'Quỳnh Tú', 'Facebook', 'https://www.facebook.com/candy.clay.9', 'D', array['Cơ hội kinh doanh'], 'Muốn xây thêm nguồn thu online, có hệ thống lâu dài, giàu có nhưng tự chủ; đã xem video mô hình và làm bài tập 3 cấp độ cuộc sống. Đã cân nhắc VIP nhưng chần chừ vì chưa có tiền.', 'Thu nhập đi làm khoảng 15 triệu/tháng, nhà thuê khoảng 20 triệu/tháng nhưng dòng tiền đang bị hút vào xây/hoàn thiện nhà và khoản nợ khoảng 2–2,5 tỷ; chưa cảm thấy tự chủ tài chính.', 'Đang cân nhắc', 'Ấm', array['Giá'], null, '2026-08-07', '2026-08-10', 'Chờ phản hồi tin nhắn hiện tại; nếu chưa phản hồi đến 10/08/2026, follow nhẹ theo cách xưng chị–em, tập trung hỏi tình hình hiện tại và không thúc tài chính/VIP.', null, 'Chưa chốt', 'Đã xem video, từng định dùng thẻ tín dụng để vào VIP nhưng Tú Quỳnh xác định cách này sẽ tạo thêm dòng tiền đỏ/áp lực nợ nên không khuyến khích. Cách xưng hô hiện tại: Tú Quỳnh xưng chị với Hạnh, gọi Hạnh là em.', '{"gia_dinh": "Chưa có.", "cong_viec": "Làm hành chính tại BVĐK Medlatec, Hà Nội; có lợi thế môi trường y tế.", "so_thich_quan_he": "Chưa có.", "money": "Lương khoảng 15M/tháng + nhà thuê khoảng 20M/tháng; dự phòng từng chia sẻ 100M; nợ khoảng 2–2,5 tỷ; dòng tiền nhà đang dùng cho công trình/khoản vay.", "suc_khoe": "Chưa có.", "mong_muon": "Muốn giàu có và tự chủ; muốn nguồn thu online/hệ thống lâu dài; bài tập từng xác định các mốc khoảng 20M, 60M+, 165M/tháng."}'::jsonb)
  returning id into v_hanh_pham;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Thanh Hưởng', 'Quỳnh Tú', 'Zalo', 'https://zalo.me/0913838739', 'D', array['Cơ hội kinh doanh'], 'Từng muốn tham gia hướng kinh doanh/đối tác; đã về Sài Gòn dự chương trình và sau đó trao đổi điện thoại nhiều lần về việc tham gia.', 'Vướng công việc/xưởng heo và tài chính nên chưa thể bắt đầu dù từng có ý định tham gia.', 'Follow', 'Lạnh', array['Giá','Thời gian'], null, '2026-08-07', '2026-08-14', 'Đã nhắn hỏi lại nhưng chưa phản hồi; nếu đến 14/08/2026 vẫn im lặng, follow nhẹ một lần, tập trung hỏi tình hình xưởng heo/công việc hiện tại và không ép quyết định.', null, 'Nuôi dưỡng', 'Lịch sử do Tú Quỳnh cung cấp: đã Zoom trao đổi; đã về Sài Gòn dự chương trình cùng Tú Quỳnh; sau đó gọi điện vài lần và từng định tham gia nhưng vướng xưởng heo và tài chính nên không vào, rồi im lặng tới hiện tại.', '{"gia_dinh": "Có yếu tố tài chính/gia đình ảnh hưởng quyết định; chưa rõ ai cùng ảnh hưởng quyết định.", "cong_viec": "Có xưởng heo/công việc là nút kẹt khiến chưa bắt đầu.", "so_thich_quan_he": "Chưa có.", "money": "Tài chính là rào cản rõ; mức sẵn sàng đầu tư hiện tại chưa xác nhận.", "suc_khoe": "Chưa có.", "mong_muon": "Từng muốn theo hướng kinh doanh/đi xa hơn; cần xác nhận lại mong muốn hiện tại."}'::jsonb)
  returning id into v_thanh_huong;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Lê Đình Cả', 'Quỳnh Tú', 'Facebook Messenger', 'https://www.facebook.com/share/17DuFQTiUo/?mibextid=wwXIfr', 'D', array['Cơ hội kinh doanh'], 'Muốn xây thêm nguồn thu 25–30M/tháng; mục tiêu quỹ 100–150M trong 6–12 tháng để chủ động chi phí gia đình và dự phòng; muốn làm online song song công việc du lịch.', 'Thu nhập 15–20M/tháng theo mùa, chưa tích lũy được nhiều; đã có gia đình và vừa có em bé nên muốn chủ động hơn về tài chính và có quỹ dự phòng.', 'Follow', 'Nóng', array['Chưa đủ thông tin','Niềm tin'], 'Nhánh KINH DOANH/ĐỐI TÁC; trước mắt cần làm rõ bản chất công việc, vai trò và lộ trình bắt đầu, chưa đề xuất gói/điều kiện Unicity cụ thể.', '2026-08-13', '2026-08-15', 'Follow nhẹ hôm nay, không gửi thêm tài liệu mới; hỏi khách đã xem video tới đâu và phần nào về công việc còn chưa rõ. Nếu khách muốn hiểu, giải thích bản chất công việc trước rồi mới hẹn review.', null, 'Chưa chốt', 'Khách đã xem/nhận video và phản hồi cảm ơn nhưng chưa có phản hồi tiếp về nội dung. SỰ THẬT: chưa biết khách đã xem xong hay chưa. Rào cản hiện tại là thiếu thông tin và niềm tin, không nên gửi thêm tài liệu hoặc đẩy CTA trước khi làm rõ bản chất công việc.', null)
  returning id into v_dinh_ca;

  insert into crm_customers (user_id, ten_khach_hang, leader_phu_trach, kenh, link_lien_he, nhanh, nhom_nhu_cau, nhu_cau_cu_the, van_de_noi_dau, giai_doan, do_nong, rao_can, giai_phap_phu_hop, lan_tuong_tac_cuoi, ngay_follow_tiep, hanh_dong_tiep_theo, gia_tri_du_kien, ket_qua, ghi_chu_ai, form_hd)
  values (v_user_id, 'Shino Nguyễn', 'Quỳnh Tú', 'Facebook Messenger', 'https://www.facebook.com/share/1GQrdTFb3M/?mibextid=wwXIfr', 'B', array['Khoá Tâm linh Tài chính'], 'Muốn tìm hướng tăng thu nhập và tích lũy để có thể mua nhà ở Hà Nội; hiện gia đình 2 vợ chồng thu nhập khoảng 15 triệu/tháng.', 'Thu nhập hiện tại của hai vợ chồng khá thấp so với mục tiêu mua nhà; có con nhỏ, chi phí gia đình khiến chỉ giữ được khoảng 7 triệu/tháng để tích lũy; đang phân vân tiếp tục tích vàng hay gửi ngân hàng.', 'Khai thác nhu cầu', 'Ấm', array['Chưa cấp thiết'], 'Chưa đề xuất; tiếp tục làm rõ khoảng cách giữa thu nhập hiện tại và mục tiêu mua nhà trước khi xác định giải pháp.', '2026-08-11', '2026-08-14', 'Gửi câu hỏi về hệ quả nếu 3–5 năm tới thu nhập vẫn giữ mức hiện tại, sau đó mới xác định hướng giải pháp phù hợp.', null, 'Chưa chốt', 'Nhánh B – Tài chính. Shino đã chủ động hỏi cách mua nhà; gia đình 2 vợ chồng thu nhập khoảng 15tr/tháng, có 1 con 2 tuổi, hiện tích lũy khoảng 7tr/tháng và đã có 2 cây vàng. Đang lo giá nhà Hà Nội tăng và chưa biết nên tiếp tục tích vàng hay chuyển sang gửi ngân hàng. Cần tiếp tục khai thác mục tiêu và khoảng cách thu nhập, không vội tư vấn sản phẩm.', null)
  returning id into v_shino;

  insert into crm_interactions (customer_id, user_id, ten_tuong_tac, thoi_gian, kenh, noi_dung, thong_tin_moi, nhu_cau_noi_dau, phan_doi_rao_can, hanh_dong_da_thuc_hien, ket_qua, buoc_tiep_theo, ngay_follow_tiep) values
  (v_thu_tham, v_user_id, '28/07/2026 – Nguyễn Thị Thu Thắm – Coaching xây nhân hiệu 1:1', '2026-07-28', null, 'Khách đăng ký xây thương hiệu cá nhân, mong muốn học 1:1 và cầm tay chỉ việc. Khách đã chuyển 8.900.000đ ngày 18/07/2026. Khách phản hồi không phù hợp học online/video dài và muốn trực tiếp làm việc với Tú Quỳnh. Khách định hướng xây nhân hiệu theo tâm linh – sức khỏe, chia sẻ đã có hành trình tu tập khoảng 3 năm và mong muốn khai tâm mở tuệ cho đời. Hai bên tiếp tục thống nhất hướng gặp trực tiếp để định vị kênh; khách được giao chuẩn bị câu chuyện gốc, đặc biệt các biến cố giai đoạn 31–33 tuổi.', null, null, null, null, null, 'Sau khi khách từ Nha Trang về, chốt buổi coaching trực tiếp; khai thác câu chuyện gốc, định vị kênh, đối tượng, thông điệp và trụ cột nội dung.', null),
  (v_thu_tham, v_user_id, '07/08/2026 - Nguyễn Thị Thu Thắm - Đăng ký coaching 1:1', '2026-08-07', 'Facebook Messenger', 'Khách đăng ký gói coaching 1:1, đã chuyển 8.900.000đ, mong muốn học trực tiếp không qua trợ lý/video', 'Đã tu tập tại các nơi thánh địa Phật khoảng 3 năm, từng tìm hiểu luân xa/năng lượng/Reiki', null, null, 'Đã gửi video/tư vấn/báo giá', null, 'Chốt lại lịch gặp trực tiếp sau khi khách đi Nha Trang về', '2026-08-20'),
  (v_que_chi, v_user_id, '[2026-07-04] – Quế Chi – Khai thác mục tiêu sức khỏe và kinh doanh', '2026-07-04', 'Zalo', 'Khách chủ động trao đổi về nhu cầu giảm cân và định hướng xây lại sự nghiệp. Khách có 11 năm kinh nghiệm Dai-ichi, từng đạt khoảng 300 triệu/tháng năm 2021; hiện ở quê, thu nhập tái tục khoảng 3–5 triệu/tháng, đang trả nợ và chưa có tích lũy. Quan tâm online, sức khỏe, xây hệ thống và muốn MLM là một phần trong hệ sinh thái riêng. Khách tự đặt mục tiêu quay lại mức 300 triệu/tháng trong 6–12 tháng.', 'Cao 1m53, 63kg. Có sứ mệnh muốn giúp 1000 phụ nữ sống tự chủ tài chính và hạnh phúc. Có kinh nghiệm bán hàng/bảo hiểm lâu năm và từng đạt thu nhập cao.', 'Muốn giảm cân/cải thiện sức khỏe, lấy lại phong độ nghề nghiệp, xây nhân hiệu và hệ thống tạo thu nhập bền vững. Khoảng cách lớn giữa giai đoạn từng thành công và tình hình tài chính hiện tại.', 'Kỳ vọng mục tiêu thu nhập 300 triệu/tháng trong 6–12 tháng cần được làm rõ và hiệu chỉnh; hiện đang trả nợ, chưa có tích lũy.', 'Phân tích lại kỳ vọng, không xác nhận hay cam kết mốc thu nhập; đề xuất tập trung xây nền sức khỏe, nhân hiệu và hệ thống trước khi đi sâu mô hình kinh doanh.', 'Quan tâm', 'Trao đổi để khách tự nhìn rõ mục tiêu 6–12 tháng thực tế, nguồn lực hiện tại và thứ tự ưu tiên; sau đó mới cân nhắc gửi tài liệu/video mô hình hiện hành.', '2026-07-06'),
  (v_thanh_huong, v_user_id, '07/08/2026 – Thanh Hưởng – Tổng hợp lịch sử và chuẩn bị follow lại', '2026-08-07', 'Zalo', 'Tú Quỳnh cung cấp lại lịch sử: khách từng Zoom trao đổi, sau đó về Sài Gòn tham dự chương trình cùng Tú Quỳnh. Sau chương trình hai bên gọi điện vài lần, khách từng định tham gia nhưng vướng xưởng heo và tài chính nên không vào và im lặng đến nay.', 'Tên Thanh Hưởng; liên hệ Zalo 0913838739; có xưởng heo/công việc cần xử lý.', 'Từng muốn đi theo hướng kinh doanh/đối tác nhưng bị kẹt bởi công việc xưởng heo và tài chính.', 'Tài chính và thời gian/công việc xưởng heo.', 'Tạo hồ sơ CRM sau khi kiểm tra không có khách trùng; tổng hợp lịch sử để chuẩn bị follow lại.', 'Follow sau', 'Nhắn hỏi thăm tình hình xưởng heo/công việc hiện tại và xác nhận mong muốn kinh doanh còn hay không; nếu còn thì làm rõ rào cản thật trước khi đề xuất giải pháp.', null),
  (v_ngoc_ha, v_user_id, '07/08/2026 – Dương Ngọc Hà – Đã nhắn reconnect, chưa phản hồi', '2026-08-07', 'Facebook', 'Tú Quỳnh đã nhắn Dương Ngọc Hà; hiện khách chưa trả lời.', null, null, null, 'Đã chủ động nhắn reconnect.', 'Chưa phản hồi', 'Nếu chưa phản hồi, follow nhẹ và hỏi thăm tình hình hiện tại/mục tiêu trước khi bàn nhịp quay lại kinh doanh.', '2026-08-10'),
  (v_thanh_huong, v_user_id, '07/08/2026 – Thanh Hưởng – Đã nhắn follow, chưa phản hồi', '2026-08-07', 'Zalo', 'Tú Quỳnh đã nhắn Thanh Hưởng; hiện khách chưa trả lời.', null, null, null, 'Đã chủ động follow lại khách.', 'Chưa phản hồi', 'Nếu vẫn im lặng, follow nhẹ một lần, hỏi tình hình xưởng heo/công việc hiện tại; không ép quyết định.', '2026-08-14'),
  (v_hanh_pham, v_user_id, '07/08/2026 – Hạnh Phạm – Đã nhắn Facebook, chưa phản hồi', '2026-08-07', 'Facebook', 'Tú Quỳnh đã nhắn Hạnh Phạm qua Facebook; hiện Hạnh chưa trả lời. Đã xác nhận link Facebook của khách và cách xưng hô: Tú Quỳnh xưng chị, gọi Hạnh là em.', 'Facebook: https://www.facebook.com/candy.clay.9. Cách xưng hô: chị–em.', null, null, 'Đã nhắn khách và cập nhật link Facebook/cách xưng hô vào CRM.', 'Chưa phản hồi', 'Nếu chưa phản hồi, follow nhẹ theo cách xưng chị–em; hỏi tình hình hiện tại, không thúc vay/quẹt thẻ hoặc vào VIP.', '2026-08-10'),
  (v_que_chi, v_user_id, '07/08/2026 – Quế Chi – Đã nhắn follow sau video, chưa phản hồi', '2026-08-07', 'Zalo', 'Tú Quỳnh đã nhắn Quế Chi; hiện khách chưa trả lời. Khách trước đó đã được gửi video giới thiệu mô hình.', null, null, null, 'Đã follow khách sau video.', 'Chưa phản hồi', 'Nếu chưa phản hồi, follow ngắn hỏi cảm nhận về video/phần phù hợp nhất và đề nghị hẹn buổi review; không nói giá hoặc cam kết thu nhập.', '2026-08-08'),
  (v_dinh_ca, v_user_id, '[2026-08-08] – Lê Đình Cả – Khai thác nhu cầu cơ hội kinh doanh', '2026-08-08', 'Facebook Messenger', 'Khách chủ động hỏi còn tìm cộng sự kinh doanh không và muốn tìm hiểu công việc để xem có duyên/hợp đồng hành. Khách hiện làm du lịch, chủ yếu sales, tổ chức tour và tư vấn khách; thu nhập khoảng 15–20M/tháng theo thời điểm/mùa. Chưa tích lũy được nhiều và muốn thêm một hướng phát triển nguồn thu, ưu tiên online song song công việc hiện tại.', 'Mục tiêu 6–12 tháng xây quỹ khoảng 100–150M; mong muốn tăng thêm 25–30M/tháng so với hiện tại; muốn nếu phù hợp thì phát triển online lâu dài.', 'Cần thêm nguồn thu và khả năng tích lũy; muốn tận dụng kỹ năng sales, tư vấn, chăm sóc khách hàng để phát triển hướng online song song.', 'Chưa đủ thông tin về thời gian, nguồn lực, mức sẵn sàng đầu tư và các yếu tố ra quyết định.', 'Ghi nhận nhu cầu và phân loại vào nhánh KINH DOANH/ĐỐI TÁC; chưa gửi giá/gói vì cần sàng lọc và tài liệu mô hình hiện hành cần được xác nhận trước.', 'Quan tâm', 'Hỏi thêm lý do muốn thay đổi, thời gian có thể dành mỗi ngày/tuần, nguồn lực hiện có và điều gì khiến khách chưa bắt đầu; nếu phù hợp mới gửi tài liệu/video mô hình hiện hành và hẹn review.', '2026-08-12'),
  (v_dinh_ca, v_user_id, '[2026-08-08] – Lê Đình Cả – Động lực xây quỹ cho gia đình và em bé', '2026-08-08', 'Facebook Messenger', 'Khách chia sẻ đã có gia đình và vừa có em bé. Mục tiêu xây quỹ 100–150 triệu nhằm phục vụ chi phí sinh hoạt gia đình và có khoản dự phòng để chủ động xử lý các vấn đề phát sinh.', 'Động lực tài chính gắn trực tiếp với trách nhiệm gia đình và em bé; mục tiêu quỹ không chỉ để tăng tài sản mà để tạo sự chủ động và an tâm.', 'Cần tăng mức chủ động tài chính, có quỹ phục vụ cuộc sống gia đình và dự phòng các tình huống phát sinh.', 'Chưa có.', 'Tiếp tục khai thác động lực và bối cảnh tài chính gia đình trước khi đối chiếu với cơ hội kinh doanh.', 'Đang trao đổi', 'Đào sâu chi phí/trách nhiệm tài chính hiện tại, mức thu nhập cần bổ sung, thời gian có thể dành và ưu tiên của gia đình trước khi giới thiệu mô hình.', '2026-08-12'),
  (v_dinh_ca, v_user_id, '[2026-08-08] – Lê Đình Cả – Xác nhận quỹ thời gian dành cho hướng mới', '2026-08-08', 'Facebook Messenger', 'Khách xác nhận có thể dành 3–4 giờ/ngày để học và triển khai lĩnh vực mới; có thể sắp xếp nhiều hơn khi công việc hiện tại không bận.', 'Quỹ thời gian dành cho hướng mới tương đối tốt và có khả năng tăng thêm theo mùa/cường độ công việc hiện tại.', 'Muốn xây nguồn thu thêm 25–30M/tháng để tiến tới quỹ 100–150M phục vụ gia đình và dự phòng.', 'Chưa có phản đối; chưa rõ mức cam kết tài chính và năng lực triển khai online.', 'Đã kiểm tra khả năng dành thời gian cho mục tiêu thu nhập mới.', 'Quan tâm', 'Khai thác mức cam kết, kinh nghiệm kinh doanh/online và nguồn lực hiện có trước khi giới thiệu mô hình.', '2026-08-10'),
  (v_dinh_ca, v_user_id, '[2026-08-09] – Lê Đình Cả – Động lực xây quỹ cho gia đình và em bé', '2026-08-09', 'Facebook Messenger', 'Khách chia sẻ mục tiêu xây quỹ 100–150M để phục vụ chi phí hằng ngày cho gia đình và chủ động xử lý các vấn đề phát sinh; khách đã có gia đình và vừa có em bé.', 'Động lực tài chính gắn trực tiếp với trách nhiệm gia đình và em bé; mục tiêu quỹ nhằm tạo sự chủ động và an tâm.', 'Muốn tăng thêm nguồn thu để xây quỹ 100–150M, trong bối cảnh thu nhập hiện tại 15–20M/tháng theo mùa và chưa tích lũy được nhiều.', 'Chưa có phản đối; chưa rõ mức sẵn sàng đầu tư và mức cam kết triển khai.', 'Ghi nhận động lực cốt lõi và tiếp tục quy trình Bước 2 – Định vị nỗi kẹt.', 'Quan tâm', 'Công nhận sự chủ động của khách, sau đó tiếp tục kể câu chuyện phù hợp và vẽ viễn cảnh thay đổi trước khi mời Guide Tìm Hiểu Kinh Doanh.', '2026-08-10'),
  (v_dinh_ca, v_user_id, '[2026-08-09] – Lê Đình Cả – Nhận diện dấu hiệu đề phòng sau khi gửi video sớm', '2026-08-09', 'Facebook Messenger', 'Rà soát lại cách dẫn dắt trước đó: thay vì kể câu chuyện và tạo thêm bối cảnh, đã gửi video ngay sau khi khách xác nhận có 3–4 giờ và đồng ý xem. Sau đó khách hỏi "Công việc đó là gì ạ. Em chưa hiểu mình sẽ làm gì".', 'Khách có nhu cầu thật nhưng chưa hình dung rõ bản chất công việc; phản hồi cho thấy cần cảm giác rõ ràng/an toàn trước khi xem tiếp mô hình.', 'Muốn xây thêm nguồn thu online song song công việc du lịch, nhưng cần hiểu mình thực sự sẽ làm gì và cách bắt đầu.', 'Có dấu hiệu đề phòng/thiếu niềm tin do chưa đủ thông tin; chưa xác định là phản đối mô hình.', 'Rà soát lịch sử và điều chỉnh hướng tư vấn: không tiếp tục đẩy video hoặc CTA; ưu tiên giải thích ngắn gọn bản chất công việc và vai trò trước.', 'Có rào cản', 'Nếu khách tiếp tục hỏi, trả lời trực tiếp công việc gồm những gì, cách làm song song công việc hiện tại và lộ trình tìm hiểu; sau đó chỉ hỏi 1 câu để xác định phần khách muốn hiểu rõ nhất.', '2026-08-10'),
  (v_dinh_ca, v_user_id, '[2026-08-09] – Lê Đình Cả – Follow sau khi gửi video mô hình', '2026-08-09', 'Facebook Messenger', 'Rà soát lịch sử: khách đã nhận video, phản hồi cảm ơn và nói sẽ xem; sau khoảng 2 ngày chưa chủ động liên hệ lại.', 'Chưa có phản hồi mới sau video.', 'Muốn tìm hướng online làm song song công việc du lịch để tăng nguồn thu và xây quỹ cho gia đình.', 'Chưa đủ thông tin; có dấu hiệu dè chừng/niềm tin do trước đó chưa hiểu rõ mình sẽ làm gì.', 'Chuẩn bị follow nhẹ, không ép quyết định; ưu tiên hỏi khách đã xem video tới đâu và mời hỏi lại phần chưa rõ.', 'Follow sau', 'Gửi một tin follow ngắn qua Messenger, không gửi thêm tài liệu mới.', '2026-08-10'),
  (v_shino, v_user_id, '[2026-08-11] – Shino Nguyễn – Khai thác mục tiêu tài chính mua nhà', '2026-08-11', 'Facebook Messenger', 'Shino chia sẻ hai vợ chồng làm công nhân, tổng thu nhập khoảng 15 triệu/tháng, có một con 2 tuổi; chi phí gia đình khiến chỉ giữ được khoảng 7 triệu/tháng để tích lũy. Đã tích được 2 cây vàng và phân vân nên tiếp tục tích vàng hay chuyển sang gửi ngân hàng vì chưa biết bao giờ đủ tiền mua nhà ở Hà Nội.', 'Đã xác nhận ngày 11/08/2026; link Facebook Messenger được cung cấp; leader phụ trách là Tú Quỳnh.', 'Muốn mua nhà ở Hà Nội nhưng cảm thấy thu nhập hiện tại của hai vợ chồng khá thấp, tốc độ tích lũy chưa đủ nhanh; lo giá vàng và giá nhà khiến mục tiêu ngày càng xa.', 'Chưa rõ nên tiếp tục tích vàng hay gửi ngân hàng; thu nhập hiện tại là điểm kẹt chính.', 'Định hướng tiếp tục làm rõ khoảng cách giữa thu nhập hiện tại và mục tiêu mua nhà trước khi đề xuất giải pháp.', 'Đang trao đổi', 'Hỏi Shino nếu 3–5 năm tới thu nhập vẫn giữ mức hiện tại thì điều gì sẽ khiến mục tiêu mua nhà khó nhất.', '2026-08-14'),
  (v_dinh_ca, v_user_id, '[2026-08-13] – Lê Đình Cả – Xác nhận follow sau video mô hình', '2026-08-13', 'Facebook Messenger', 'Rà soát đoạn chat: khách từng hỏi rõ công việc là gì, sau đó nhận video mô hình và phản hồi cảm ơn; hiện chưa có phản hồi tiếp về nội dung video.', 'Chưa có thông tin mới về mức độ đã xem video; cần xác nhận nhẹ trước khi giải thích tiếp.', 'Muốn xây thêm nguồn thu online 25–30M/tháng và quỹ 100–150M trong 6–12 tháng để chủ động chi phí gia đình, dự phòng; có thể dành 3–4 giờ/ngày.', 'Chưa đủ thông tin và niềm tin; trước đó khách từng nói chưa hình dung mình sẽ làm gì.', 'Xác nhận lại lịch sử và định hướng follow nhẹ, không gửi thêm tài liệu mới; ưu tiên hỏi khách đã xem video tới đâu và phần nào còn chưa rõ.', 'Follow sau', 'Nhắn follow ngắn qua Messenger. Nếu khách đã xem, hỏi phần nào về công việc còn chưa rõ rồi giải thích trực tiếp; nếu chưa xem, hẹn một mốc xem cụ thể.', '2026-08-15');
end $$;
