-- KHO CHUNG — 120 hook/tiêu đề tổng hợp từ tài liệu "Kho Hook Thumbnail Caption" do người dùng gửi.
-- Đã lọc bỏ các đoạn dở dang ("…"), trùng lặp và phần bình luận/phân tích không phải tiêu đề thật.
-- Chạy 1 lần trong Supabase SQL Editor. An toàn để chạy lại (chỉ insert thêm, không xoá dữ liệu cũ).

insert into hooks_bank_shared (hook_text, category, note) values
('Mình là ai sau 12 tháng nữa?', 'cau_hoi_goi_mo', 'Tỉnh thức - phát triển bản thân'),
('Luật hấp dẫn trong tình yêu', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Nghệ thuật giữ tiền trong lúc có tiền', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Hạnh phúc trong tĩnh lặng', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Cách để Facebook tự đẩy bài lên xu hướng', 'to_mo_bo_ngo', 'Xây kênh - content'),
('Chữ Thuận – thứ pháp giúp cuộc đời hanh thông', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Còn thở thì còn gỡ', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Sự thật về Chú Đại Bi mà bạn nhất định nên biết', 'su_that_phu_phang', 'Tỉnh thức - phát triển bản thân'),
('Còn nghèo thì bớt chill lại', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('4 dấu hiệu cho biết bạn đang bước vào đại vận tốt', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Kinh doanh càng to, lợi nhuận càng mỏng', 'lat_nguoc_niem_tin', 'Tài chính - tâm linh'),
('Nếu có tư duy này, bạn sẽ không còn nghèo nữa', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('12 biểu hiện của một người thiên địa nhân đều phải nể phục', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Phúc 7 đời người đàn ông có người vợ biết tu', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Vai trò của người con dâu trong phước nghiệp của nhà chồng', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Cách dưỡng tâm để tướng tự đẹp lên', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Tiền đầy trong ví sẽ biết có gì trong lòng người', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Người có phước, nhiều người ghét; người vô phước, ghét nhiều người', 'nghich_ly', 'Nhân quả - phước đức'),
('Thùng rỗng kêu to', 'nghich_ly', 'Tỉnh thức - phát triển bản thân'),
('Chỉ sợ trời phạt không thương, chứ sợ gì người thương không quý', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('5 thứ cần làm sau khi phá sản', 'con_so_cu_the', 'Tài chính - tâm linh'),
('Vì sao phụ nữ càng giỏi càng dễ bất hạnh?', 'cau_hoi_goi_mo', 'Phụ nữ - nội lực'),
('Nếu nhận ra điều này, bạn sẽ thay đổi ngoạn mục', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Sau 30 tuổi, cuộc sàng lọc lớn nhất của cuộc đời chính thức bắt đầu', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Làm sao để tích lũy phước báu?', 'cau_hoi_goi_mo', 'Nhân quả - phước đức'),
('Nhìn người chồng, bạn có thể biết phúc đức tiền kiếp đã gieo?', 'cau_hoi_goi_mo', 'Tài chính - tâm linh'),
('Phước phần lớn nhất là gặp được người tốt lúc khốn khó', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Khi bạn là người có tu tập, có đạo đức, cuộc đời sẽ thay đổi thế nào?', 'cau_hoi_goi_mo', 'Nhân quả - phước đức'),
('3 nguyên tắc vàng để tránh tai họa', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('10 điều cần lưu ý trong năm 2026', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Bốn báu vật của một gia đình hưng vượng', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Mỗi sáng thức dậy, hãy nhớ những điều này để giữ phước', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Học cách thương lấy chính mình', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Cái tôi vị tế – sự nguy hiểm của tri thức khi thiếu tỉnh thức', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Các chu kỳ 7 năm của cuộc đời', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Tử tế bắt đầu từ cơ thể, lan ra cuộc sống', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Kìm nén dục không tạo ra thanh tịnh', 'loi_sai_pho_bien', 'Tỉnh thức - phát triển bản thân'),
('Tâm cầu nối với vận mệnh như thế nào?', 'cau_hoi_goi_mo', 'Tỉnh thức - phát triển bản thân'),
('Đừng tùy tiện bước vào nhân quả của người khác', 'loi_sai_pho_bien', 'Nhân quả - phước đức'),
('7 dấu hiệu “vận may” đang đến rất gần', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Bài khảo khó vượt qua nhất của con người là ái tình', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Lúc ở đỉnh cao danh vọng, điều gì mới thật sự đáng giữ?', 'cau_hoi_goi_mo', 'Tỉnh thức - phát triển bản thân'),
('4 sai lầm cha mẹ đang làm tổn phước báu của con mình', 'con_so_cu_the', 'Hôn nhân - gia đình'),
('Thói quen buổi sáng thu hút tài lộc', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Nếu bạn có 3 đặc điểm này, bạn nhất định phải giữ lấy', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Tôi vô tình mở khóa “chế độ thần” trong chính mình', 'thu_nhan_ca_nhan', 'Tỉnh thức - phát triển bản thân'),
('5 điều chứng tỏ một người phụ nữ đẳng cấp', 'con_so_cu_the', 'Phụ nữ - nội lực'),
('Nhân quả ở đời: bạn chỉ đang gặp lại những gì mình đã gieo', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Khi con người hấp dẫn nhất', 'truoc_sau', 'Tỉnh thức - phát triển bản thân'),
('Khi phụ nữ bắt đầu sống vì mình', 'truoc_sau', 'Phụ nữ - nội lực'),
('9 dấu hiệu bạn đang tự tạo phước cho chính mình', 'con_so_cu_the', 'Nhân quả - phước đức'),
('Khi đã hiểu được luật nhân quả', 'truoc_sau', 'Nhân quả - phước đức'),
('Cách cư xử của người khôn ngoan', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('2026 là năm cuộc chơi đổi luật, đường đua thuộc về những người có điều này', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Có những người đến với đời bạn gọi là phúc, cũng có người là bài học', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Bớt khoe, cuộc sống càng hạnh phúc', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('99% phụ nữ sẽ khổ nếu không bỏ thói quen này', 'to_mo_bo_ngo', 'Phụ nữ - nội lực'),
('Phân biệt tiếng nói nội tâm với nỗi sợ trong đầu', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('2 câu thần chú về bảo hộ và chữa lành', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('5 dấu hiệu của người có hào quang mạnh', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Để được Facebook mời kiếm tiền từ nội dung, bạn cần điều gì?', 'cau_hoi_goi_mo', 'Tài chính - tâm linh'),
('Quy tắc im lặng: không phải cái gì cũng nên cho người khác biết', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('15 dấu hiệu tâm linh ban đêm cần lưu ý', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('5 dấu hiệu phát tài', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Dấu hiệu của người mang phúc khí lớn', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Muốn biết nhân quả của một người, hãy nghe cách họ nói về người khác', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Bão không đến để đánh gục bạn, bão đến để dạy bạn cách đứng vững', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Tại sao phụ nữ nhạy tâm linh thường phải làm dâu gia tộc nặng nghiệp?', 'cau_hoi_goi_mo', 'Nhân quả - phước đức'),
('Trên đời có hai ánh sáng không cần ai vỗ tay', 'lat_nguoc_niem_tin', 'Tỉnh thức - phát triển bản thân'),
('Đôi khi cách duy nhất để sống sót là biết “từ bỏ”', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Gia tiên không cần mâm cao cỗ đầy, họ cần ánh sáng từ tâm thức của bạn', 'to_mo_bo_ngo', 'Gia tiên - tâm linh'),
('Khi biết quay về tập trung vào chính mình, ta sẽ dần thôi so sánh hơn – thua', 'truoc_sau', 'Tỉnh thức - phát triển bản thân'),
('Nếu chỉ cần chăm là giàu, thì con trâu đã là tỷ phú', 'nghich_ly', 'Tài chính - tâm linh'),
('2026 cần bỏ 3 thứ: cuộc chơi vô nghĩa, người thân coi thường và bạn bè giả tạo', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Muốn tích phước báu trong hôn nhân, hãy nhớ những điều này', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Nếu mẹ bạn vẫn còn trên đời, hãy một lần ngồi thật sâu và hỏi mẹ những câu này', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Hóa ra mình không hiểu mẹ mình nhiều như mình nghĩ', 'su_that_phu_phang', 'Hôn nhân - gia đình'),
('Người Cha Giàu đã dạy gì về cách người giàu nhìn tiền?', 'cau_hoi_goi_mo', 'Tài chính - tâm linh'),
('Tài chính không sụp đổ vào ngày bạn mua thứ đắt nhất', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Người bất hiếu thường khó thuận đường', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Phật cao một thước, ma cao một trượng', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('9 dấu hiệu bạn là người có nhân quả tốt', 'con_so_cu_the', 'Nhân quả - phước đức'),
('Gia tiên vẫn đi sau lưng con, nhìn thấu từng nỗi con phải chịu', 'to_mo_bo_ngo', 'Gia tiên - tâm linh'),
('Ta như chiếc lá khô, chỉ biết thả mình theo dòng đời', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Những mốc trả nghiệp trong cuộc đời', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Càng trưởng thành, càng ít giải thích', 'lat_nguoc_niem_tin', 'Tỉnh thức - phát triển bản thân'),
('Phước không tự nhiên mà có: 9 dấu hiệu bạn đang tự tích phước', 'con_so_cu_the', 'Nhân quả - phước đức'),
('7 dấu hiệu đại vận đang mở', 'con_so_cu_the', 'Tỉnh thức - phát triển bản thân'),
('Người có phúc khí lớn thường có những biểu hiện này', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('4 dấu hiệu gia tiên đang che chở bạn', 'con_so_cu_the', 'Gia tiên - tâm linh'),
('Khi vận đổi, cuộc đời thường xuất hiện những tín hiệu này', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Có những mối quan hệ xuất hiện để trả duyên, không phải để đi cùng cả đời', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Muốn biết một người có phước hay không, hãy nhìn cách họ đối xử khi không ai nhìn thấy', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Người càng có phước càng biết giữ miệng', 'lat_nguoc_niem_tin', 'Nhân quả - phước đức'),
('Có những cái mất không phải mất phước, mà là nghiệp đang rời đi', 'canh_bao_mat_mat', 'Nhân quả - phước đức'),
('Một gia đình bắt đầu hưng vượng khi trong nhà có người hiểu điều này', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Người phụ nữ biết tu chính mình có thể thay đổi khí vận cả gia đình', 'to_mo_bo_ngo', 'Hôn nhân - gia đình'),
('Tiền bạc cũng có nhân quả: cách bạn đối xử với tiền đang tạo ra tương lai tài chính', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Không phải cứ làm nhiều là giàu, quan trọng là bạn đang làm đúng việc hay không', 'su_that_phu_phang', 'Tài chính - tâm linh'),
('Có những người càng cố kiếm tiền càng nghèo vì không biết mình đang rò rỉ ở đâu', 'lat_nguoc_niem_tin', 'Tài chính - tâm linh'),
('Vận may không tự nhiên xuất hiện, nó thường đến sau một chuỗi thay đổi bên trong', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Khi phước đủ, người đúng và cơ hội đúng sẽ tự xuất hiện', 'truoc_sau', 'Nhân quả - phước đức'),
('Đừng vội oán khi cuộc đời lấy đi một thứ: đôi khi đó chính là cách nghiệp được kết thúc', 'loi_sai_pho_bien', 'Nhân quả - phước đức'),
('Người biết đủ không nghèo; người không biết đủ, có bao nhiêu vẫn thiếu', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Thứ làm một người hao phước nhanh nhất đôi khi không phải việc họ làm, mà là lời họ nói', 'canh_bao_mat_mat', 'Nhân quả - phước đức'),
('Càng muốn đổi vận, càng phải nhìn lại những nhân mình đang gieo mỗi ngày', 'lat_nguoc_niem_tin', 'Tỉnh thức - phát triển bản thân'),
('Không phải ai rời khỏi đời bạn cũng là mất mát', 'canh_bao_mat_mat', 'Tỉnh thức - phát triển bản thân'),
('Có những cánh cửa đóng lại chính là phước', 'to_mo_bo_ngo', 'Nhân quả - phước đức'),
('Khi một người bắt đầu tỉnh thức, họ sẽ dần rời khỏi những cuộc chơi này', 'truoc_sau', 'Tỉnh thức - phát triển bản thân'),
('Người thật sự có phước thường không cần chứng minh mình có phước', 'lat_nguoc_niem_tin', 'Nhân quả - phước đức'),
('Một người bắt đầu đổi vận khi họ ngừng đổ lỗi cho hoàn cảnh', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Muốn biết tương lai của mình, hãy nhìn những lựa chọn mình đang lặp lại mỗi ngày', 'to_mo_bo_ngo', 'Tỉnh thức - phát triển bản thân'),
('Người càng tỉnh càng biết thứ gì phải giữ, thứ gì phải bỏ', 'lat_nguoc_niem_tin', 'Tỉnh thức - phát triển bản thân'),
('Đừng cầu tài lộc khi những thói quen này vẫn đang âm thầm làm hao tài', 'loi_sai_pho_bien', 'Tài chính - tâm linh'),
('Tiền không ở lại với người chỉ biết kiếm mà không biết giữ', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Một người kiếm được nhiều tiền chưa chắc đã có năng lực giữ tiền', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Khi tâm loạn, tiền cũng rất khó tụ', 'truoc_sau', 'Tài chính - tâm linh'),
('Có những khoản tiền đến để làm giàu, cũng có những khoản tiền đến để thử lòng', 'to_mo_bo_ngo', 'Tài chính - tâm linh'),
('Phước của một người đôi khi được nhìn thấy rõ nhất qua cách họ vượt qua nghịch cảnh', 'to_mo_bo_ngo', 'Nhân quả - phước đức');
